app = '{{ project_name }}'

[env]
  DJANGO_SETTINGS_MODULE = '{{ project_name }}.settings.dev'
  PYTHONDONTWRITEBYTECODE = '1'
  PYTHONUNBUFFERED = '1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/'
