version: 2.1
jobs:
  build-python:
    docker:
      - image: cimg/python:3.9.13
    environment:
      TMPDIR: /var/tmp
    working_directory: ~/
    steps:
      - checkout:
          path: template
      - run:
          name: Create virtual environment
          command: python -m venv venv
      - run:
          name: Install Django
          command: |
            . venv/bin/activate
            pip install pip --upgrade
            DJANGO_REQ="$(cat ~/template/requirements/base.txt | grep -i django | head -n 1)"
            readonly DJANGO_REQ
            pip install "${DJANGO_REQ}"
      - run:
          name: Generate project
          command: |
            . venv/bin/activate
            django-admin startproject \
              --template ~/template \
              --extension py,md \
              example
      - run:
          name: Run tests
          command: |
            pushd example
            python -m venv venv
            . venv/bin/activate
            pip install pip --upgrade
            pip install --requirements requirements/dev.txt
            python manage.py makemigrations
            python manage.py test
workflows:
  test:
    jobs:
      - build-python
