version: 2.1
jobs:
  build-python:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: python -m venv venv
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pip install pip-tools --upgrade
            pip-sync requirements/dev.txt
            ./manage.py makemigrations
            ./manage.py test
workflows:
  test:
    jobs:
      - build-python
