version: 2.1
jobs:
  build-python:
    docker:
      - image: cimg/python:3.9.13
    environment:
      - TMPDIR: /var/tmp
      - TEMPLATE_DIR: ~/template
    steps:
      - checkout:
          path: ~/template
      - run:
          name: Create virtual environment
          command: python -m venv venv
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install pip --upgrade
            DJANGO_REQ="$(cat "${TEMPLATE_DIR}/requirements/base.txt" | grep -i django | head -n 1)"
            readonly DJANGO_REQ
            pip install "${DJANGO_REQ}"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            django-admin startproject \
              --template "${TEMPLATE_DIR}" \
              --extension py,md \
              example .
            python manage.py makemigrations
            python manage.py test
workflows:
  test:
    jobs:
      - build-python
